### list all messages
GET http://localhost:3000/messages

### create new message
POST http://localhost:3000/messages
content-Type: application/json

{
    "content": "yeah right!!"
}

### get a specific message
GET http://localhost:3000/messages/61af5099-b53a-468a-a4c2-17e5ecd3c31f