### list all messages
GET http://localhost:3000/messages

### create new message
POST http://localhost:3000/messages
content-Type: application/json

{
    "content": "gzv"
}

### get a specific message
GET http://localhost:3000/messages/543