### list all messages
GET http://localhost:3000/messages

### create new message
POST http://localhost:3000/messages
content-Type: application/json

{
    "content": "after adding DI"
}

### get a specific message
GET http://localhost:3000/messages/213d9756-f1ad-4b4d-8a8c-54e19850f2dd